### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by cenchaojun** [KingJamesSong/DisentangleSaliency#1]
thank you for your nice work. Your new idea about the cascaded detail modeling and body filling model is very impressive, but I still have some unclear details about the implementation.May I ask you how the visualization of Figure 9 in the paper. just print attention feature? could you release some codes?
![image](https://user-images.githubusercontent.com/48192514/189477580-77356686-e1b8-4886-837a-53d595aafe88.png)
best wish ❤️

**Comment by KingJamesSong** [comment]
Thanks for your interest in our work!

Regarding the left visualization of attention, we just download the attention map and visualize it using Matlab colormap (https://nl.mathworks.com/help/matlab/ref/colormap.html). 

Thanks again and it is more than welcome to pose further comments!

Happy Mid-Autumn Festival

**Comment by cenchaojun** [comment]
> Thanks for your interest in our work!
> 
> Regarding the left visualization of attention, we just download the attention map and visualize it using Matlab colormap (https://nl.mathworks.com/help/matlab/ref/colormap.html).
> 
> Thanks again and it is more than welcome to pose further comments!
> 
> Happy Mid-Autumn Festival

Thank you for your quick reply.
Happy Mid-Autumn Festival.😄
